// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyqkkwjcarvqlrezkryj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cWtrd2pjYXJ2cWxyZXprcnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0Nzk0MjMsImV4cCI6MjA2MTA1NTQyM30.F1n7sZcPy5zziJT_6wH12dL2oDFItei4Au98p7kI0Vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);